### ISSUE TITLE
Won't pass travis build when ggraph, ggforce or igraph are in the package. 

### ISSUE THREAD

**Issue by theoroe3** [jr-packages/jrTidyverse2#2]

**Comment by theoroe3** [comment]
igraph fixed, ggraph still breaking

**Comment by csgillespie** [comment]
ggforce looks like it has problems.

https://cran.r-project.org/web/checks/check_results_ggforce.html

I'll try one or two tricks. Do you need ggforce?

**Comment by theoroe3** [comment]
We don't directly need ggforce, but i believe ggraph needs ggforce. 

ggforce isn't in the imports for jrTidyverse2

**Comment by theoroe3** [comment]
@csgillespie  is this sorted ?

**Comment by csgillespie** [comment]
Fixed - stole the apt-get bit from the travis.yml file in githhub, ggforce
